spring:
  application:
    name: rueckgabe-service
  artemis:
    broker-url: tcp://localhost:61616

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

